blank_issues_enabled: false
contact_links: []
issue_templates:
  - name: 掲載のないギフトの追加要望
    description: Request to add a gift not currently included
    labels: [add]
    file: add_request.md

  - name: 間違いの指摘、修正要望
    description: Error report / Correction request
    labels: [fix]
    file: fix_request.md

